local theme = require("colors")[require("utils.fun").get_scheme()]

return {
  copy_mode = {
    text = " 󰆏 COPY ",
    bg = theme.brights[3],
    mappings = {
      { "Esc", "exit" },
      { "hjkl", "move" },
      { "y", "copy" },
      { "HML", "viewport top/mid/bot" },
      { "v", "visual" },
      { "V", "v-line" },
      { "C-v", "v-block" },
      { "w", "word forward" },
      { "b", "word backwards" },
      { "e", "word end" },
      { "g", "go top" },
      { "G", "go bot" },
      { ",;", "repeat forward/backwards" },
    },
  },
  search_mode = {
    text = " 󰍉 SEARCH ",
    bg = theme.brights[4],
    mappings = {
      { "Esc", "quit" },
      { "C-n", "next" },
      { "C-N", "prev" },
      { "C-r", "cycle type" },
      { "C-u", "clear pattern" },
      { "PageUp", "prev page" },
      { "PageDown", "next page" },
    },
  },
  window_mode = {
    text = " 󱂬 WINDOW ",
    bg = theme.ansi[6],
    mappings = {
      { "Esc", "quit" },
      { "q", "close" },
      { "hjkl", "move" },
      { "v", "vsplit" },
      { "s", "hsplit" },
      { "p", "pick" },
      { "x", "swap" },
      { "o", "toggle zoom" },
      { "+><-", "resize pane" },
    },
  },
  font_mode = {
    text = " 󰛖 FONT ",
    bg = theme.indexed[16] or theme.ansi[8],
    mappings = {
      { "Esc", "quit" },
      { "+", "increase size" },
      { "-", "decrease size" },
      { "0", "reset size" },
    },
  },
  lock_mode = { text = "  LOCK ", bg = theme.ansi[8] },
  help_mode = {
    text = " 󰞋 NORMAL ",
    bg = theme.ansi[5],
    mappings = {
      { "C-(S-)Tab", "next/prev tab" },
      { "C-S-t", "new tab" },
      { "C-S-w", "close tab" },
      { "C-S-c", "copy" },
      { "C-S-v", "paste" },
      { "C-S-l", "debug" },
      { "C-S-u", "char select" },
      { "<leader>w", "window mode" },
      { "<leader>f", "font mode" },
      { "<leader>s", "search mode" },
      { "<leader>c", "copy mode" },
    },
  },
}
